On branch master  Your branch is up to date with 'origin/master'.
 Changes to be committed:
	typechange: bitbake/bbTutorial/build/tmp/work/first-0.1-r1/temp/log.do_build
	typechange: bitbake/bbTutorial/build/tmp/work/first-0.1-r1/temp/log.do_listtasks
	typechange: bitbake/bbTutorial/build/tmp/work/first-0.1-r1/temp/log.do_patch
	typechange: bitbake/bbTutorial/build/tmp/work/first-0.1-r1/temp/run.do_build
	typechange: bitbake/bbTutorial/build/tmp/work/first-0.1-r1/temp/run.do_listtasks
	typechange: bitbake/bbTutorial/build/tmp/work/first-0.1-r1/temp/run.do_patch
	typechange: bitbake/bbTutorial/build/tmp/work/myvar-0.1-r1/temp/log.do_build
	typechange: bitbake/bbTutorial/build/tmp/work/myvar-0.1-r1/temp/log.do_myvar_py
	typechange: bitbake/bbTutorial/build/tmp/work/myvar-0.1-r1/temp/run.do_build
	typechange: bitbake/bbTutorial/build/tmp/work/myvar-0.1-r1/temp/run.do_myvar_py
	typechange: bitbake/bbTutorial/build/tmp/work/varbuild-0.1-r1/temp/log.do_build
	typechange: bitbake/bbTutorial/build/tmp/work/varbuild-0.1-r1/temp/run.do_build
	modified:   impedance_match
	modified:   jtag/stm32/factory.sh
	typechange: jtag/stm32/fw
	typechange: jtag/stm32/fwl
	typechange: nodejs/zeromq/node_modules/.bin/node-gyp-build
	typechange: nodejs/zeromq/node_modules/.bin/node-gyp-build-optional
	typechange: nodejs/zeromq/node_modules/.bin/node-gyp-build-test
	modified:   ssh_tunnel.sh

diff --git a/jtag/stm32/fwl b/jtag/stm32/fwl
--- a/jtag/stm32/fwl
+++ b/jtag/stm32/fwl
@@ -1,1 +1,74 @@
-flash_write_lock.sh
+#!/bin/bash
+
+if [ ${#1} -eq 0 ]; then
+	echo "usage: $0 image-file"
+    exit 0
+fi
+
+CURRENT_DIR=$(cd $(dirname $0); pwd)
+
+#xxx.hex or xxx.bin
+IMAGE_FILE=$1
+
+#stm32f103rbt6
+#FLASH_ADDR=0x08000000
+#FLASH_SIZE=0x00020000
+
+#stm32f103c8t6
+#FLASH_ADDR=0x08000000
+#FLASH_SIZE=0x00010000
+
+#stm32f103cbt6
+FLASH_ADDR=0x08000000
+FLASH_SIZE=0x00020000
+
+${CURRENT_DIR}/probe.sh
+
+if [ $? -ne 0 ]; then
+    echo "probe fail!"
+    exit 1
+fi
+
+EXT="${IMAGE_FILE##*.}"
+echo EXT: $EXT
+
+#flash write_image erase xxx.hex;
+#flash write_image erase xxx.bin 0x08000000;
+
+if [ "${EXT}" == "hex" ]; then
+    TARGET="$IMAGE_FILE"
+elif [ "${EXT}" == "bin" ]; then
+    TARGET="$IMAGE_FILE $FLASH_ADDR"
+else
+    echo "illegal suffix [$EXT]"
+    exit 1
+fi
+
+
+#CONFIG=${CURRENT_DIR}/tcl/target/stm32f1x_sysfsgpio_swd.cfg
+CONFIG=${CURRENT_DIR}/tcl/target/stm32f1x_cmsisdap.cfg
+
+#CONFIG=${CURRENT_DIR}/tcl/target/stm32f0x_cmsisdap.cfg
+#CONFIG=${CURRENT_DIR}/tcl/target/stm32f1x_bcm2835gpio_swd.cfg
+
+#set FLASH_SIZE 0x20000
+
+sudo openocd -s ${CURRENT_DIR}/tcl -f ${CONFIG} -c \
+"   init;
+    halt;
+    reset halt;
+    flash write_image erase ${TARGET};
+    reset;
+    shutdown;
+"
+
+sudo openocd -s ${CURRENT_DIR}/tcl -f ${CONFIG} -c \
+"   init;
+    halt;
+    reset halt;
+    stm32f1x lock 0
+    reset halt;
+    shutdown;
+"
+
+exit $?
